export type StaticCatalogLanguage = "en" | "zh-CN";

export type StaticCatalogSkill = {
  name: string;
  description: string;
};

type CatalogUi = {
  title: string;
  summary: string;
  searchPlaceholder: string;
  totalLabel: string;
  visibleLabel: string;
  themeLabel: string;
  skillBadge: string;
  copyTitle: string;
  copiedLabel: string;
  emptyTitle: string;
  emptyHint: string;
  footer: string;
};

const uiByLanguage: Record<StaticCatalogLanguage, CatalogUi> = {
  en: {
    title: "Skill Port Catalog",
    summary: "Browse and search the Agent Skills in this shared catalog.",
    searchPlaceholder: "Search names or descriptions…",
    totalLabel: "Total",
    visibleLabel: "Showing",
    themeLabel: "Toggle theme",
    skillBadge: "Agent Skill",
    copyTitle: "Copy Skill name",
    copiedLabel: "Copied",
    emptyTitle: "No matching Skills",
    emptyHint: "Try another name or description.",
    footer: "Generated by Skill Port"
  },
  "zh-CN": {
    title: "Skill Port 技能目录",
    summary: "浏览并搜索这份可分享目录中的 Agent Skills。",
    searchPlaceholder: "搜索技能名称或描述…",
    totalLabel: "技能总数",
    visibleLabel: "当前显示",
    themeLabel: "切换主题",
    skillBadge: "Agent Skill",
    copyTitle: "复制 Skill 名称",
    copiedLabel: "已复制",
    emptyTitle: "未找到匹配技能",
    emptyHint: "请尝试其他名称或描述。",
    footer: "由 Skill Port 生成"
  }
};

export function renderStaticCatalog(
  skills: StaticCatalogSkill[],
  language: StaticCatalogLanguage = "en"
): string {
  const ui = uiByLanguage[language];
  const data = scriptSafeJson({ skills, ui });
  return `<!doctype html>
<html lang="${language}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="Skill Port">
  <meta name="description" content="${escapeHtml(ui.summary)}">
  <link rel="icon" href="data:,">
  <title>${escapeHtml(ui.title)}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f6f4ef;
      --surface: #fffdf9;
      --surface-muted: #eeebe3;
      --text: #1d201d;
      --muted: #686b65;
      --border: #dcd8ce;
      --accent: #b64f28;
      --accent-soft: #f5e3d9;
      --shadow: 0 16px 45px rgba(49, 42, 33, .08);
    }
    [data-theme="dark"] {
      color-scheme: dark;
      --bg: #151714;
      --surface: #1e211d;
      --surface-muted: #292d27;
      --text: #f3f1ea;
      --muted: #a8aca2;
      --border: #383d35;
      --accent: #eb8a5c;
      --accent-soft: #3d2b23;
      --shadow: 0 18px 50px rgba(0, 0, 0, .3);
    }
    * { box-sizing: border-box; }
    html { background: var(--bg); scroll-behavior: smooth; }
    body {
      min-height: 100vh;
      margin: 0;
      background:
        radial-gradient(circle at 80% 0, color-mix(in srgb, var(--accent) 9%, transparent), transparent 34rem),
        var(--bg);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
    }
    button, input { font: inherit; }
    .layout {
      display: grid;
      grid-template-columns: 18rem minmax(0, 1fr);
      min-height: 100vh;
    }
    .sidebar {
      position: sticky;
      top: 0;
      height: 100vh;
      padding: 2.5rem 2rem;
      border-right: 1px solid var(--border);
      background: color-mix(in srgb, var(--surface) 94%, transparent);
      backdrop-filter: blur(14px);
    }
    .brand {
      margin: 0;
      font-family: ui-serif, Georgia, "Songti SC", serif;
      font-size: 1.55rem;
      letter-spacing: -.025em;
    }
    .brand-note {
      margin: .5rem 0 2rem;
      color: var(--muted);
      font-size: .82rem;
    }
    .search {
      width: 100%;
      border: 1px solid var(--border);
      border-radius: .7rem;
      padding: .78rem .9rem;
      background: var(--bg);
      color: var(--text);
      outline: none;
    }
    .search:focus {
      border-color: var(--accent);
      box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent) 18%, transparent);
    }
    .stats {
      display: grid;
      gap: .45rem;
      margin: 1.35rem 0;
      color: var(--muted);
      font-size: .8rem;
    }
    .stats strong { color: var(--accent); }
    .theme {
      width: 100%;
      margin-top: 1rem;
      border: 1px solid var(--border);
      border-radius: .7rem;
      padding: .65rem .8rem;
      background: var(--surface-muted);
      color: var(--text);
      cursor: pointer;
    }
    .theme:hover { border-color: var(--accent); }
    main { min-width: 0; padding: 4.5rem clamp(1.5rem, 5vw, 5rem); }
    .content { width: min(76rem, 100%); margin: 0 auto; }
    .hero {
      margin-bottom: 2.5rem;
      padding-bottom: 2.5rem;
      border-bottom: 1px solid var(--border);
    }
    h1 {
      max-width: 12ch;
      margin: 0 0 1rem;
      font-family: ui-serif, Georgia, "Songti SC", serif;
      font-size: clamp(2.6rem, 7vw, 5.4rem);
      line-height: 1;
      letter-spacing: -.055em;
    }
    .hero p { max-width: 42rem; margin: 0; color: var(--muted); font-size: 1.08rem; }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(min(18rem, 100%), 1fr));
      gap: 1rem;
    }
    .card {
      display: flex;
      min-height: 12rem;
      flex-direction: column;
      gap: 1rem;
      padding: 1.35rem;
      border: 1px solid var(--border);
      border-radius: 1rem;
      background: var(--surface);
      box-shadow: 0 1px 0 rgba(0, 0, 0, .02);
      transition: transform .18s ease, border-color .18s ease, box-shadow .18s ease;
    }
    .card:hover {
      transform: translateY(-3px);
      border-color: var(--accent);
      box-shadow: var(--shadow);
    }
    .card-head { display: flex; align-items: flex-start; justify-content: space-between; gap: .7rem; }
    .skill-name {
      border: 0;
      border-radius: .45rem;
      padding: .32rem .55rem;
      background: var(--accent-soft);
      color: var(--accent);
      cursor: pointer;
      font-family: ui-monospace, SFMono-Regular, Consolas, monospace;
      font-size: .86rem;
      font-weight: 700;
      overflow-wrap: anywhere;
      text-align: left;
    }
    .skill-name:hover, .skill-name.copied { background: var(--accent); color: #fff; }
    .badge {
      flex: none;
      color: var(--muted);
      font-size: .68rem;
      letter-spacing: .08em;
      text-transform: uppercase;
    }
    .description { margin: 0; color: var(--muted); font-size: .94rem; }
    .empty {
      padding: 5rem 1rem;
      color: var(--muted);
      text-align: center;
    }
    .empty h2 { margin: 0 0 .5rem; color: var(--text); }
    footer {
      display: flex;
      justify-content: space-between;
      margin-top: 4rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--border);
      color: var(--muted);
      font-size: .75rem;
    }
    [hidden] { display: none !important; }
    @media (max-width: 760px) {
      .layout { display: block; }
      .sidebar {
        position: relative;
        width: auto;
        height: auto;
        padding: 1.25rem;
        border-right: 0;
        border-bottom: 1px solid var(--border);
      }
      .brand-note { margin-bottom: 1rem; }
      .stats { grid-template-columns: 1fr 1fr; margin: .8rem 0; }
      .theme { margin-top: 0; }
      main { padding-top: 2.5rem; }
      h1 { max-width: none; font-size: 2.5rem; }
    }
  </style>
</head>
<body>
  <div class="layout">
    <aside class="sidebar">
      <h2 class="brand">${escapeHtml(ui.title)}</h2>
      <p class="brand-note">${escapeHtml(ui.summary)}</p>
      <label>
        <span hidden>${escapeHtml(ui.searchPlaceholder)}</span>
        <input id="search" class="search" type="search" placeholder="${escapeHtml(ui.searchPlaceholder)}" autocomplete="off">
      </label>
      <div class="stats" aria-live="polite">
        <span>${escapeHtml(ui.totalLabel)} <strong id="total">0</strong></span>
        <span>${escapeHtml(ui.visibleLabel)} <strong id="visible">0</strong></span>
      </div>
      <button id="theme" class="theme" type="button">${escapeHtml(ui.themeLabel)}</button>
    </aside>
    <main>
      <div class="content">
        <header class="hero">
          <h1>${escapeHtml(ui.title)}</h1>
          <p>${escapeHtml(ui.summary)}</p>
        </header>
        <section id="grid" class="grid" aria-label="${escapeHtml(ui.title)}"></section>
        <section id="empty" class="empty" hidden>
          <h2>${escapeHtml(ui.emptyTitle)}</h2>
          <p>${escapeHtml(ui.emptyHint)}</p>
        </section>
        <footer><span>${escapeHtml(ui.footer)}</span><span id="footer-count"></span></footer>
      </div>
    </main>
  </div>
  <script id="catalog-data" type="application/json">${data}</script>
  <script>
    (function () {
      "use strict";
      var payload = JSON.parse(document.getElementById("catalog-data").textContent || "{\\"skills\\":[]}");
      var skills = Array.isArray(payload.skills) ? payload.skills : [];
      var ui = payload.ui;
      var search = document.getElementById("search");
      var grid = document.getElementById("grid");
      var empty = document.getElementById("empty");
      var visible = document.getElementById("visible");

      function normalize(value) {
        return String(value).toLocaleLowerCase().replace(/\\s+/g, " ").trim();
      }

      function fallbackCopy(value) {
        var textarea = document.createElement("textarea");
        textarea.value = value;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand("copy");
        textarea.remove();
      }

      async function copyName(button, name) {
        try {
          if (!navigator.clipboard) throw new Error("Clipboard API unavailable");
          await navigator.clipboard.writeText(name);
        } catch (_) {
          fallbackCopy(name);
        }
        var previous = button.textContent;
        button.textContent = ui.copiedLabel;
        button.classList.add("copied");
        window.setTimeout(function () {
          button.textContent = previous;
          button.classList.remove("copied");
        }, 1100);
      }

      function makeCard(skill) {
        var article = document.createElement("article");
        article.className = "card";
        var head = document.createElement("div");
        head.className = "card-head";
        var name = document.createElement("button");
        name.type = "button";
        name.className = "skill-name";
        name.title = ui.copyTitle;
        name.textContent = skill.name;
        name.addEventListener("click", function () { copyName(name, skill.name); });
        var badge = document.createElement("span");
        badge.className = "badge";
        badge.textContent = ui.skillBadge;
        var description = document.createElement("p");
        description.className = "description";
        description.textContent = skill.description;
        head.append(name, badge);
        article.append(head, description);
        return article;
      }

      function render() {
        var query = normalize(search.value);
        var filtered = skills.filter(function (skill) {
          return !query || normalize(skill.name).includes(query) || normalize(skill.description).includes(query);
        });
        grid.replaceChildren();
        var fragment = document.createDocumentFragment();
        filtered.forEach(function (skill) { fragment.appendChild(makeCard(skill)); });
        grid.appendChild(fragment);
        visible.textContent = String(filtered.length);
        empty.hidden = filtered.length !== 0;
      }

      function preferredTheme() {
        try {
          var saved = localStorage.getItem("skill-port-catalog-theme");
          if (saved === "light" || saved === "dark") return saved;
        } catch (_) {}
        return window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
      }

      function setTheme(theme) {
        document.documentElement.dataset.theme = theme;
        try { localStorage.setItem("skill-port-catalog-theme", theme); } catch (_) {}
      }

      document.getElementById("total").textContent = String(skills.length);
      document.getElementById("footer-count").textContent = ui.totalLabel + ": " + skills.length;
      document.getElementById("theme").addEventListener("click", function () {
        setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark");
      });
      search.addEventListener("input", render);
      search.addEventListener("keydown", function (event) {
        if (event.key === "Escape") {
          search.value = "";
          render();
        }
      });
      setTheme(preferredTheme());
      render();
    })();
  </script>
</body>
</html>
`;
}

function scriptSafeJson(value: unknown): string {
  return JSON.stringify(value).replace(/[<>&\u2028\u2029]/g, (character) => {
    const code = character.codePointAt(0)!.toString(16).padStart(4, "0");
    return `\\u${code}`;
  });
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#039;");
}
